
import React from 'react';

const CommunityPage: React.FC = () => {
  return (
    <div className="max-w-6xl mx-auto">
      <div className="text-center mb-12">
        <h2 className="text-4xl font-bold text-slate-900 display-font mb-4">Design Community</h2>
        <p className="text-slate-500 max-w-2xl mx-auto">
          Explore amazing designs generated by the Recto community. Get inspired, remix, and share your own masterpieces.
        </p>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6 opacity-60">
        {[...Array(12)].map((_, i) => (
          <div key={i} className="bg-white rounded-2xl border border-slate-200 overflow-hidden shadow-sm">
            <div className="aspect-[3/4] bg-slate-100">
              <img src={`https://picsum.photos/seed/community-${i}/300/400`} alt="Community design" className="w-full h-full object-cover" />
            </div>
            <div className="p-3 flex items-center justify-between">
              <div className="flex items-center space-x-2">
                <div className="w-6 h-6 rounded-full bg-slate-200"></div>
                <span className="text-xs font-medium text-slate-600">User_{i}</span>
              </div>
              <div className="flex items-center space-x-1 text-slate-400">
                <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
                  <path d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z" />
                </svg>
                <span className="text-xs">{Math.floor(Math.random() * 100)}</span>
              </div>
            </div>
          </div>
        ))}
      </div>
      
      <div className="mt-12 p-8 bg-indigo-50 border-2 border-dashed border-indigo-200 rounded-3xl text-center">
        <h3 className="text-xl font-bold text-indigo-900 mb-2">Community Voting Coming Soon!</h3>
        <p className="text-indigo-700/70">We're building a space where you can vote for the best AI designers and win rewards.</p>
      </div>
    </div>
  );
};

export default CommunityPage;
